[Zend Opcache]
; Uncomment the following line to enable Opcache
;zend_extension = opcache.so
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 60
opcache.fast_shutdown = 1
opcache.enable_cli = 1

; Uncomment the following two lines only after you know what you are doing.
;opcache.jit = 1255
;opcache.jit_buffer_size = 64M
