[global]
pid = @@SERVBAY_BASE_FULL_PATH@@/tmp/php-fpm-@@PHP_VERSION@@.pid
error_log = @@SERVBAY_BASE_FULL_PATH@@/logs/php/@@PHP_VERSION@@/php-fpm.log
log_level = notice

[www]
listen = @@SERVBAY_BASE_FULL_PATH@@/tmp/php-cgi-@@PHP_VERSION@@.sock
listen.backlog = -1
listen.allowed_clients = 127.0.0.1
;listen.owner = www
;listen.group = www
listen.mode = 0666
;user = www
;group = www
pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 6
pm.max_requests = 1024
pm.process_idle_timeout = 10s
request_terminate_timeout = 100
request_slowlog_timeout = 0
slowlog = @@SERVBAY_BASE_FULL_PATH@@/logs/php/@@PHP_VERSION@@/slow.log
; enable error log
php_flag[display_errors] = on
php_admin_value[error_log] = @@SERVBAY_BASE_FULL_PATH@@/logs/php/@@PHP_VERSION@@/errors.log
php_admin_flag[log_errors] = on